#!/bin/bash

#=============================================================================
wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh

bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/miniconda

export PATH="$HOME/miniconda/bin:$PATH"

#=============================================================================
conda create -n FERRET -c conda-forge pyferret ferret_datasets --yes

source activate FERRET

#=============================================================================
pip install ferretmagic==2016.10.28


