#!/bin/bash

set -ex

#==================================================
jupyter nbextension enable --py widgetsnbextension --sys-prefix

#==================================================
git clone https://github.com/PBrockmann/fast

pyferretActivate=/srv/conda/envs/notebook/etc/conda/activate.d/pyferret-activate.sh

echo '' >> $pyferretActivate
echo '=========================================' >> $pyferretActivate
echo 'export FER_DATA=". $FER_DATA $HOME/fast"' >> $pyferretActivate
echo 'export FER_GO=". $FER_GO $HOME/fast"' >> $pyferretActivate
echo 'export FER_PALETTE=". /$FER_PALETTE $HOME/fast"' >> $pyferretActivate
echo 'export PATH="$FER_DIR/bin:$HOME/fast:$PATH"' >> $pyferretActivate
