#!/bin/bash

set -ex

jupyter nbextension enable --py widgetsnbextension --sys-prefix

git clone https://github.com/PBrockmann/fast

export FER_DATA=". ${FER_DATA} /home/jovyan/fast"
export FER_GO=". ${FER_GO} /home/jovyan/fast"
export FER_PALETTE=". /${FER_PALETTE} /home/jovyan/fast"
export PATH="${FER_DIR}/bin:/home/jovyan/fast:${PATH}"
